apiVersion: v1
kind: Service
metadata:
  namespace: kubecost
  name: prometheus-public
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30900
  selector:
    app: prometheus
    component: server
    release: kubecost
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: kubecost
  name: grafana-public
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30901
  selector:
    app: grafana
    release: kubecost
  type: NodePort
