apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-public
  labels:
    app: cassandra
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
    # We use a different public port just to make sure that we don't interfere with Cassandra's discovery mechanism.
    - port: 9043
      targetPort: 9042
