# permissions for end users to view costefficiencyslomappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: costefficiencyslomapping-viewer-role
rules:
- apiGroups:
  - slo.sloc.github.io
  resources:
  - costefficiencyslomappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slo.sloc.github.io
  resources:
  - costefficiencyslomappings/status
  verbs:
  - get
