# permissions for end users to view cpuusageslomappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpuusageslomapping-viewer-role
rules:
- apiGroups:
  - slo.polaris-slo-cloud.github.io
  resources:
  - cpuusageslomappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slo.polaris-slo-cloud.github.io
  resources:
  - cpuusageslomappings/status
  verbs:
  - get
