# permissions for end users to edit cpuusagesloapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpuusagesloapplication-editor-role
rules:
- apiGroups:
  - slo.sloc.github.io
  resources:
  - cpuusagesloapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slo.sloc.github.io
  resources:
  - cpuusagesloapplications/status
  verbs:
  - get
