
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling
  resources:
  - hpa
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - horizontalelasticitystrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - horizontalelasticitystrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - templatestrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - templatestrategies/status
  verbs:
  - get
  - patch
  - update
