
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - '*/scale'
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - horizontalelasticitystrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - horizontalelasticitystrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - templatestrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - templatestrategies/status
  verbs:
  - get
  - patch
  - update
