# permissions for end users to view templatestrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatestrategy-viewer-role
rules:
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - templatestrategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticitystrategies.sloc.github.io
  resources:
  - templatestrategies/status
  verbs:
  - get
