# permissions for end users to edit templatestrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatestrategy-editor-role
rules:
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - templatestrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - templatestrategies/status
  verbs:
  - get
