# permissions for end users to edit verticalelasticitystrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticalelasticitystrategy-editor-role
rules:
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - verticalelasticitystrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticity.polaris-slo-cloud.github.io
  resources:
  - verticalelasticitystrategies/status
  verbs:
  - get
