apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mesh-keystore-manual
    namespace: mesh
    files:
      - keystore.jceks
    literals:
      - password=secret
    type: Opaque