apiVersion: elasticitystrategies.sloc.github.io/v1
kind: HorizontalElasticityStrategy
metadata:
  name: horizontalelasticitystrategy-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twitter-clone
  currSloCompliance: 2.0

