apiVersion: metrics.polaris-slo-cloud.github.io/v1
kind: CostEfficiencyMetricMapping
metadata:
  name: costefficiencymetricmapping-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mesh-gentics-mesh
  metricConfig:
    targetThreshold: 90
