apiVersion: slo.sloc.github.io/v1
kind: CPUUsageSloMapping
metadata:
  name: cpuusageslomapping-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twitter-clone
  targetAvgCPUUtilizationPercentage: 70
