apiVersion: slo.sloc.github.io/v1
kind: CPUUsageSloMapping
metadata:
  name: cpuusageslomapping-sample
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twitter-clone
  elasticityStrategy:
    apiVersion: elasticity.sloc.github.io/v1
    kind: HorizontalElasticityStrategy
  sloConfig:
    targetAvgCPUUtilizationPercentage: 70
  staticElasticityStrategyConfig:
    test: 0
    test1: abc
    complexObj:
      a: 1
      b: test

