apiVersion: v1
kind: Service
metadata:
  namespace: kubecost
  name: kubecost-service
spec:
  type: NodePort
  selector:
    app: cost-analyzer
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30907
