apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: polaris
  name: polaris-ui
spec:
  selector:
    matchLabels:
      app: polaris-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: polaris-ui
    spec:
      containers:
      - name: polaris-ui
        image: polarissloc/polaris-ui
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: polaris
  name: polaris-ui
spec:
  selector:
    app: polaris-ui
  type: NodePort
  ports:
  - port: 80
    nodePort: 30908
    targetPort: 80
