apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
# This uses the `gitlab+deploy-token-1` for getting read access to git.dsg.tuwien.ac.at:5005/sloc/testbed-docker-registry
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXQuZHNnLnR1d2llbi5hYy5hdDo1MDA1Ijp7InVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi0xIiwicGFzc3dvcmQiOiI2Y3IzWlhaWFhITXNSWFZWNGF6ZyIsImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTB4T2paamNqTmFXRnBZV0VoTmMxSllWbFkwWVhwbiJ9fX0=
metadata:
  name: dsg-gitlab-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-clone
spec:
  selector:
    matchLabels:
      app: twitter-clone
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter-clone
    spec:
      containers:
      - name: twitter-clone
        image: git.dsg.tuwien.ac.at:5005/sloc/testbed-docker-registry/twitter-clone
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
            - name: LISTEN_PORT
              value: "8080"
            - name: CASSANDRA_NODE
              value: "cassandra-test-cluster-dc1-nodes"
            - name: CASSANDRA_PORT
              value: "9042"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsg-gitlab-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-clone-service
spec:
  selector:
    app: twitter-clone
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30903
    targetPort: 8080
